version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - [%(threadName)s] - %(name)s:%(lineno)d  - [%(levelname)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/lightbulbflow.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  scrapers:
    level: DEBUG
    handlers: [ console, file ]
    propagate: false

root:
  level: INFO
  handlers: [ console, file ]